
var usaStates = new Array(
	new Array("State of Alabama","AL"),
	new Array("State of Alaska","AK"),
	new Array("State of Arizona","AZ"),
	new Array("State of Arkansas","AR"),
	new Array("State of California","CA"),
	new Array("State of Colorado","CO"),
	new Array("State of Connecticut","CT"),
	new Array("State of Delaware","DE"),
	new Array("District of Columbia","DC"),
	new Array("State of Florida","FL"),
	new Array("State of Georgia","GA"),
	new Array("State of Hawaii","HI"),
	new Array("State of Idaho","ID"),
	new Array("State of Illinois","IL"),
	new Array("State of Indiana","IN"),
	new Array("State of Iowa","IA"),
	new Array("State of Kansas","KS"),
	new Array("Commonwealth of Kentucky","KY"),
	new Array("State of Louisiana","LA"),
	new Array("State of Maine","ME"),
	new Array("State of Maryland","MD"),
	new Array("Commonwealth of Massachusetts","MA"),
	new Array("State of Michigan","MI"),
	new Array("State of Minnesota","MN"),
	new Array("State of Mississippi","MS"),
	new Array("State of Missouri","MO"),
	new Array("State of Montana","MT"),
	new Array("State of Nebraska","NE"),
	new Array("State of Nevada","NV"),
	new Array("State of New Hampshire","NH"),
	new Array("State of New Jersey","NJ"),
	new Array("State of New Mexico","NM"),
	new Array("State of New York","NY"),
	new Array("State of North Carolina","NC"),
	new Array("State of North Dakota","ND"),
	new Array("State of Ohio","OH"),
	new Array("State of Oklahoma","OK"),
	new Array("State of Oregon","OR"),
	new Array("Commonwealth of Pennsylvania","PA"),
	new Array("State of Rhode Island and Providence Plantations","RI"),
	new Array("State of South Carolina","SC"),
	new Array("State of South Dakota","SD"),
	new Array("State of Tennessee","TN"),
	new Array("State of Texas","TX"),
	new Array("State of Utah","UT"),
	new Array("State of Vermont","VT"),
	new Array("Commonwealth of Virginia","VA"),
	new Array("State of Washington","WA"),
	new Array("State of West Virginia","WV"),
	new Array("State of Wisconsin","WI"),
	new Array("State of Wyoming","WY")
)